import { NextResponse } from "next/server";

export async function GET() {
  const agents = [
    {
      id: "agent-commander",
      name: "Commander",
      role: "Orchestrator",
      model: "Amazon Nova Pro",
      status: "active",
      uptime: 99.9,
      taskCount: 47,
      lastAction: "Dispatched auto-scale to Monitor Agent",
      lastActionTime: "2025-01-15T14:32:00Z",
      capabilities: [
        "task_routing",
        "incident_escalation",
        "deployment_management",
        "agent_coordination",
      ],
      tools: ["monitor_agent", "analyst_agent", "voice_agent", "dashboard_agent"],
      memoryUsage: "128MB",
      avgResponseTime: "1.2s",
    },
    {
      id: "agent-monitor",
      name: "Monitor",
      role: "Infrastructure Watcher",
      model: "Amazon Nova Lite",
      status: "processing",
      uptime: 99.8,
      taskCount: 183,
      lastAction: "Analyzing Redis cache metrics anomaly",
      lastActionTime: "2025-01-15T14:35:00Z",
      capabilities: [
        "metric_collection",
        "threshold_monitoring",
        "anomaly_detection",
        "alert_generation",
      ],
      tools: ["cloudwatch_reader", "prometheus_query", "health_checker"],
      memoryUsage: "64MB",
      avgResponseTime: "0.8s",
    },
    {
      id: "agent-analyst",
      name: "Analyst",
      role: "Root Cause Analysis",
      model: "Amazon Nova Pro",
      status: "active",
      uptime: 99.7,
      taskCount: 34,
      lastAction: "Correlating latency spike with deploy v2.14.2",
      lastActionTime: "2025-01-15T14:28:00Z",
      capabilities: [
        "root_cause_analysis",
        "log_correlation",
        "pattern_detection",
        "recommendation_engine",
      ],
      tools: ["log_analyzer", "trace_correlator", "metric_analyzer"],
      memoryUsage: "256MB",
      avgResponseTime: "3.5s",
    },
    {
      id: "agent-voice",
      name: "Voice",
      role: "Natural Language Interface",
      model: "Amazon Nova Sonic",
      status: "idle",
      uptime: 99.9,
      taskCount: 12,
      lastAction: "Processed voice command: 'status report'",
      lastActionTime: "2025-01-15T14:10:00Z",
      capabilities: [
        "speech_to_text",
        "natural_language_understanding",
        "command_parsing",
        "voice_response",
      ],
      tools: ["speech_recognizer", "intent_parser", "tts_engine"],
      memoryUsage: "96MB",
      avgResponseTime: "0.5s",
    },
    {
      id: "agent-dashboard",
      name: "Dashboard",
      role: "Visualization Engine",
      model: "Amazon Nova Canvas",
      status: "active",
      uptime: 100.0,
      taskCount: 291,
      lastAction: "Updated real-time metrics feed",
      lastActionTime: "2025-01-15T14:35:00Z",
      capabilities: [
        "data_visualization",
        "report_generation",
        "real_time_updates",
        "chart_rendering",
      ],
      tools: ["chart_generator", "report_builder", "data_aggregator"],
      memoryUsage: "192MB",
      avgResponseTime: "0.3s",
    },
  ];

  return NextResponse.json({
    timestamp: new Date().toISOString(),
    total: agents.length,
    active: agents.filter((a) => a.status === "active").length,
    processing: agents.filter((a) => a.status === "processing").length,
    idle: agents.filter((a) => a.status === "idle").length,
    agents,
    hierarchy: {
      root: "agent-commander",
      children: [
        "agent-monitor",
        "agent-analyst",
        "agent-voice",
        "agent-dashboard",
      ],
      pattern: "agents-as-tools",
      description:
        "Commander orchestrates sub-agents as tools using Strands Agents SDK",
    },
  });
}
